import React, { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';

export default function DurantProposalReview({ workOrderId, onApproved }: { workOrderId: string; onApproved: () => void }) {
  const [proposal, setProposal] = useState<any>(null);
  const [notes, setNotes] = useState<any[]>([]);
  const [history, setHistory] = useState<any[]>([]);
  const [returnNote, setReturnNote] = useState('');
  const [message, setMessage] = useState('');
  async function load() { const [p, n, h] = await Promise.all([supabase.from('durant_proposals').select('*').eq('work_order_id', workOrderId).maybeSingle(), supabase.from('durant_shared_notes').select('*').eq('work_order_id', workOrderId).order('created_at'), supabase.from('durant_history').select('*').eq('work_order_id', workOrderId).order('created_at')]); setProposal(p.data); setNotes(n.data || []); setHistory(h.data || []); }
  useEffect(() => { if (workOrderId) void load(); }, [workOrderId]);
  if (!proposal && !notes.length && !history.length) return <div className="rounded border border-purple-500/40 bg-purple-950/20 p-3 text-sm text-purple-100">No Durant proposal yet. Shared notes and QR history will appear here.</div>;
  return <section className="rounded border border-purple-400/60 bg-purple-950/20 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-bold text-purple-100">Durant Media Review</h3><span className="rounded-full border border-purple-400 px-2 py-1 text-xs font-bold">{proposal?.status || 'notes only'}</span></div>{proposal ? <><pre className="mt-3 max-h-56 overflow-auto whitespace-pre-wrap rounded bg-zinc-950 p-3 text-xs text-zinc-200">{JSON.stringify(proposal.proposed_data, null, 2)}</pre>{proposal.status === 'ready' ? <div className="mt-3 flex flex-wrap gap-2"><button className="rounded bg-neon-green px-3 py-2 font-bold text-black" onClick={async () => { const { error } = await supabase.rpc('approve_durant_proposal', { target_proposal_id: proposal.id }); if (error) setMessage(error.message); else { setMessage('Durant changes approved and applied.'); await load(); onApproved(); } }}>Approve Changes</button><input className="min-w-56 flex-1 rounded border border-zinc-700 bg-zinc-900 px-3" placeholder="Required return note" value={returnNote} onChange={e => setReturnNote(e.target.value)} /><button className="rounded border border-amber-400 px-3 py-2 text-amber-200" disabled={!returnNote.trim()} onClick={async () => { const { error } = await supabase.from('durant_proposals').update({ status: 'returned', return_note: returnNote.trim(), updated_at: new Date().toISOString() }).eq('id', proposal.id); if (error) setMessage(error.message); else { setReturnNote(''); setMessage('Returned for changes.'); await load(); } }}>Return for Changes</button></div> : null}</> : null}{message ? <p className="mt-2 text-sm text-neon-green">{message}</p> : null}<div className="mt-4 grid gap-3 md:grid-cols-2"><div><h4 className="text-sm font-bold">Shared Notes</h4>{notes.map(row => <p key={row.id} className="mt-1 border-l-2 border-purple-500 pl-2 text-xs"><time className="text-zinc-500">{new Date(row.created_at).toLocaleString()}</time><br/>{row.body}</p>)}</div><div><h4 className="text-sm font-bold">History</h4>{history.map(row => <p key={row.id} className="mt-1 text-xs"><time className="text-zinc-500">{new Date(row.created_at).toLocaleString()}</time><br/><strong>{row.summary}</strong></p>)}</div></div></section>;
}
