import React, { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';

const money = (value: unknown) => Number.isFinite(Number(value)) ? `$${Number(value).toFixed(2)}` : '—';
const safeHttpUrl = (value: unknown) => /^https?:\/\/[^\s]+$/i.test(String(value || '').trim()) ? String(value).trim() : '';

export default function DurantProposalReview({ workOrderId, onApproved }: { workOrderId: string; onApproved: () => void }) {
  const [proposal, setProposal] = useState<any>(null);
  const [notes, setNotes] = useState<any[]>([]);
  const [history, setHistory] = useState<any[]>([]);
  const [returnNote, setReturnNote] = useState('');
  const [message, setMessage] = useState('');
  const [open, setOpen] = useState(false);
  async function load() {
    const [p, n, h] = await Promise.all([
      supabase.from('durant_proposals').select('*').eq('work_order_id', workOrderId).maybeSingle(),
      supabase.from('durant_shared_notes').select('*').eq('work_order_id', workOrderId).order('created_at'),
      supabase.from('durant_history').select('*').eq('work_order_id', workOrderId).order('created_at'),
    ]);
    setProposal(p.data); setNotes(n.data || []); setHistory(h.data || []);
  }
  useEffect(() => { if (workOrderId) void load(); }, [workOrderId]);
  const status = proposal?.status || (notes.length || history.length ? 'notes only' : 'waiting');
  const data = proposal?.proposed_data || {};
  return <>
    <section className="rounded border border-purple-400/60 bg-purple-950/20 p-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold text-purple-100">Durant Media</h3><p className="text-xs text-purple-200/70">Pricing, links, findings, notes, and review history</p></div><div className="flex items-center gap-2"><span className="rounded-full border border-purple-400 px-2 py-1 text-xs font-bold capitalize">{status}</span><button type="button" className="rounded bg-purple-500 px-3 py-2 text-sm font-bold text-white" onClick={() => setOpen(true)}>View Durant Entries</button></div></div></section>
    {open ? <div className="fixed inset-0 z-[100500] flex items-center justify-center bg-black/80 p-3" role="dialog" aria-modal="true" aria-label="Durant Media Entries" onMouseDown={event => { if (event.target === event.currentTarget) setOpen(false); }}><section className="flex max-h-[94vh] w-full max-w-5xl flex-col overflow-hidden rounded-xl border border-purple-400/70 bg-zinc-950 shadow-2xl">
      <header className="flex items-center justify-between gap-3 border-b border-zinc-700 bg-purple-950/40 p-4"><div><h2 className="text-xl font-black text-purple-100">Durant Media Entries</h2><p className="text-xs text-zinc-400">Review these entries before applying them to GadgetBoy POS.</p></div><button type="button" className="rounded border border-zinc-600 px-3 py-2" onClick={() => setOpen(false)}>Close</button></header>
      <div className="min-h-0 overflow-y-auto p-4">
        {proposal ? <><div className="grid gap-3 md:grid-cols-2">{(data.items || []).map((item: any, index: number) => { const partUrl = safeHttpUrl(item.partUrl); const invoiceUrl = safeHttpUrl(item.invoiceUrl); return <article key={item.id || index} className="rounded-lg border border-zinc-700 bg-zinc-900 p-4"><h3 className="font-bold text-white">{item.repair || item.description || item.name || item.partName || `Line item ${index + 1}`}</h3><p className="mt-1 text-xs text-zinc-400">{item.device || item.repairCategory || 'Work-order item'}</p><dl className="mt-3 grid grid-cols-3 gap-2 text-sm"><div><dt className="text-xs text-zinc-500">Durant cost</dt><dd>{money(item.partCost ?? item.cost)}</dd></div><div><dt className="text-xs text-zinc-500">Markup</dt><dd>{Number(item.markupPct || 0).toFixed(1)}%</dd></div><div><dt className="text-xs text-zinc-500">Client price</dt><dd>{money(item.parts ?? item.price)}</dd></div></dl><div className="mt-4 flex flex-wrap gap-2">{partUrl ? <a href={partUrl} target="_blank" rel="noreferrer" className="rounded border border-[#39FF14]/70 px-3 py-2 text-sm font-bold text-[#39FF14]">Open Part URL</a> : <span className="rounded border border-zinc-700 px-3 py-2 text-sm text-zinc-500">No part URL</span>}{invoiceUrl ? <a href={invoiceUrl} target="_blank" rel="noreferrer" className="rounded border border-purple-400 px-3 py-2 text-sm font-bold text-purple-200">Open Invoice</a> : <span className="rounded border border-zinc-700 px-3 py-2 text-sm text-zinc-500">No invoice</span>}</div></article>; })}</div>
          <div className="mt-4 grid gap-3 md:grid-cols-3"><article className="rounded border border-zinc-700 bg-zinc-900 p-3"><h3 className="text-xs font-bold uppercase text-zinc-500">Labor charge</h3><p className="mt-1 text-lg font-bold">{money(data.laborCost)}</p></article><article className="rounded border border-zinc-700 bg-zinc-900 p-3"><h3 className="text-xs font-bold uppercase text-zinc-500">Transfer</h3><p className="mt-1 font-bold">{data.durantFullTransfer ? 'Full Transfer' : 'Remains with GadgetBoy'}</p></article>{safeHttpUrl(data.invoiceUrl) ? <a href={safeHttpUrl(data.invoiceUrl)} target="_blank" rel="noreferrer" className="rounded border border-purple-400 bg-purple-950/30 p-3 font-bold text-purple-200">Open General Invoice</a> : <article className="rounded border border-zinc-700 bg-zinc-900 p-3 text-zinc-500">No general invoice</article>}</div><article className="mt-4 rounded border border-zinc-700 bg-zinc-900 p-4"><h3 className="font-bold">Findings</h3><p className="mt-2 whitespace-pre-wrap text-sm text-zinc-300">{data.findings || 'No findings entered.'}</p></article></> : <p className="rounded border border-zinc-700 bg-zinc-900 p-4 text-zinc-400">No Durant proposal has been submitted yet.</p>}
        <div className="mt-4 grid gap-3 md:grid-cols-2"><section><h3 className="font-bold">Shared Notes</h3>{notes.length ? notes.map(row => <article key={row.id} className="mt-2 border-l-2 border-purple-500 bg-zinc-900 p-2 text-sm"><time className="text-xs text-zinc-500">{new Date(row.created_at).toLocaleString()}</time><p className="mt-1 whitespace-pre-wrap">{row.body}</p></article>) : <p className="mt-2 text-sm text-zinc-500">No shared notes.</p>}</section><section><h3 className="font-bold">History</h3>{history.length ? history.map(row => <article key={row.id} className="mt-2 rounded bg-zinc-900 p-2 text-sm"><time className="text-xs text-zinc-500">{new Date(row.created_at).toLocaleString()}</time><p className="mt-1 font-semibold">{row.summary}</p></article>) : <p className="mt-2 text-sm text-zinc-500">No history yet.</p>}</section></div>
        {proposal?.status === 'ready' ? <div className="sticky bottom-0 mt-5 flex flex-wrap gap-2 border-t border-zinc-700 bg-zinc-950 py-3"><button className="rounded bg-[#39FF14] px-4 py-2 font-bold text-black" onClick={async () => { const { error } = await supabase.rpc('approve_durant_proposal', { target_proposal_id: proposal.id }); if (error) setMessage(error.message); else { setMessage('Durant changes approved and applied.'); await load(); onApproved(); } }}>Approve Changes</button><input className="min-w-56 flex-1 rounded border border-zinc-700 bg-zinc-900 px-3 py-2" placeholder="Required return note" value={returnNote} onChange={event => setReturnNote(event.target.value)} /><button className="rounded border border-amber-400 px-4 py-2 text-amber-200 disabled:opacity-40" disabled={!returnNote.trim()} onClick={async () => { const { error } = await supabase.from('durant_proposals').update({ status: 'returned', return_note: returnNote.trim(), updated_at: new Date().toISOString() }).eq('id', proposal.id); if (error) setMessage(error.message); else { setReturnNote(''); setMessage('Returned for changes.'); await load(); } }}>Return for Changes</button></div> : null}{message ? <p className="mt-2 text-sm text-[#39FF14]">{message}</p> : null}
      </div>
    </section></div> : null}
  </>;
}
