import React, { useEffect, useMemo, useState } from 'react';
import RepairTypeManager from '../repairs/RepairTypeManager';
import DeviceForm from '../repairs/DeviceForm';
import VendorsWindow from './VendorsWindow';
import { consumeWindowPayload } from '../lib/windowPayload';
import { normalizeInventoryDefaults, normalizeRepairDefaults } from '../lib/catalogDefaults';
import { normalizeCleanupSettings } from '../lib/workOrderLifecycle';
import { previewWorkOrderCleanup, reconcileLegacyWorkOrders } from '../lib/workOrderCleanup';

const DEFAULT_PART_TYPES = ['Screen', 'Battery', 'Charging Port', 'Camera', 'Speaker', 'Microphone', 'Buttons', 'Housing', 'Motherboard', 'Power Supply', 'Cable', 'Adhesive', 'Other'];
function useShopSettings() { const api = (window as any).api; const [record, setRecord] = useState<any>({}); useEffect(() => { void api?.dbGet?.('settings').then((rows: any[]) => setRecord(Array.isArray(rows) ? rows[0] || {} : {})).catch(() => {}); }, [api]); async function save(patch: any) { const payload = { ...record, ...patch, updatedAt: new Date().toISOString() }; const saved = record?.id != null ? await api?.dbUpdate?.('settings', record.id, payload) : await api?.dbAdd?.('settings', { ...payload, createdAt: new Date().toISOString() }); setRecord({ ...payload, ...(saved || {}) }); } return { record, save }; }

function InventoryTypesSettings() {
  const { record, save: saveSettings } = useShopSettings(); const [types, setTypes] = useState<string[]>(DEFAULT_PART_TYPES); const [value, setValue] = useState(''); const [editing, setEditing] = useState('');
  useEffect(() => { if (Array.isArray(record?.inventoryPartTypes) && record.inventoryPartTypes.length) setTypes(record.inventoryPartTypes); }, [record]);
  const sorted = useMemo(() => [...types].sort((a, b) => a.localeCompare(b)), [types]);
  async function persist(next: string[]) { const normalized = Array.from(new Set(next.map(item => item.trim()).filter(Boolean))); setTypes(normalized); await saveSettings({ inventoryPartTypes: normalized }); }
  async function commit() { const name = value.trim(); if (!name) return; await persist(editing ? types.map(item => item === editing ? name : item) : [...types, name]); setValue(''); setEditing(''); }
  return <section className="flex h-full min-h-0 flex-col"><div><h2 className="text-lg font-bold">Part Types</h2><p className="mt-1 text-xs text-zinc-400">Manage the saved choices used by the Inventory Part Type field.</p></div><div className="mt-4 flex flex-wrap gap-2"><input value={value} onChange={event => setValue(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') void commit(); }} placeholder={editing ? 'Rename part type' : 'Add part type'} className="min-w-[190px] flex-1 rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2 outline-none focus:border-[#39FF14]"/><button onClick={() => void commit()} className="rounded-lg bg-[#39FF14] px-4 font-bold text-black">{editing ? 'Rename' : 'Add'}</button>{editing ? <button onClick={() => { setEditing(''); setValue(''); }} className="rounded-lg border border-zinc-700 px-3">Cancel</button> : null}</div><div className="mt-4 min-h-0 flex-1 overflow-auto rounded-xl border border-zinc-700 bg-zinc-950/50">{sorted.map(type => <div key={type} className="flex items-center justify-between border-b border-zinc-800 px-4 py-3 last:border-0"><strong>{type}</strong><div className="flex gap-2"><button onClick={() => { setEditing(type); setValue(type); }} className="rounded border border-zinc-700 px-3 py-1 text-xs">Edit</button><button onClick={() => void persist(types.filter(item => item !== type))} className="rounded border border-red-500/60 px-3 py-1 text-xs text-red-300">Remove</button></div></div>)}</div></section>;
}

function DefaultsSettings({ kind }: { kind: 'inventory' | 'repairs' }) {
  const { record, save } = useShopSettings(); const current = useMemo(() => kind === 'inventory' ? normalizeInventoryDefaults(record?.inventoryDefaults) : normalizeRepairDefaults(record?.repairDefaults), [kind, record]); const [draft, setDraft] = useState<any>(current); const [saved, setSaved] = useState(false); useEffect(() => setDraft(current), [current]);
  const field = (key: string, label: string, type = 'number') => <label className="block"><span className="mb-1 block text-xs font-semibold text-zinc-400">{label}</span><input type={type} value={draft[key] ?? ''} onChange={event => setDraft((value: any) => ({ ...value, [key]: type === 'number' ? Number(event.target.value) : event.target.value }))} className="w-full rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2 outline-none focus:border-[#39FF14]"/></label>;
  return <section className="mx-auto h-full max-w-3xl overflow-auto"><h2 className="text-lg font-bold">{kind === 'inventory' ? 'Inventory Defaults' : 'Repair Defaults'}</h2><p className="mt-1 text-xs text-zinc-400">Defaults apply only to new entries. Existing records are never overwritten.</p><div className="mt-5 grid gap-4 rounded-xl border border-zinc-700 bg-zinc-950/50 p-4 sm:grid-cols-2">{kind === 'inventory' ? <>{field('markupPct', 'Default Markup %')}{field('lowStockThreshold', 'Low Stock Threshold')}{field('reorderQty', 'Default Reorder Quantity')}<label className="block"><span className="mb-1 block text-xs font-semibold text-zinc-400">Condition Choices</span><input value={(draft.conditions || []).join(', ')} onChange={event => setDraft((value: any) => ({ ...value, conditions: event.target.value.split(',').map((item: string) => item.trim()).filter(Boolean) }))} className="w-full rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2"/></label></> : <>{field('repairCategory', 'Default Repair Type', 'text')}{field('laborCost', 'Default Labor Charge')}</>}</div><div className="mt-4 flex items-center justify-end gap-3"><span className="text-xs text-[#39FF14]">{saved ? 'Defaults saved.' : ''}</span><button onClick={() => void save(kind === 'inventory' ? { inventoryDefaults: normalizeInventoryDefaults(draft) } : { repairDefaults: normalizeRepairDefaults(draft) }).then(() => { setSaved(true); window.setTimeout(() => setSaved(false), 2500); })} className="rounded-lg bg-[#39FF14] px-5 py-2 text-sm font-bold text-black">Save Defaults</button></div></section>;
}

function TicketCleanupSettings() {
  const { record, save } = useShopSettings();
  const [draft, setDraft] = useState(() => normalizeCleanupSettings(record?.ticketCleanupSettings));
  const [preview, setPreview] = useState({ scanned: 0, diagnosticOnly: 0, universal: 0, total: 0 });
  const [message, setMessage] = useState('');
  useEffect(() => setDraft(normalizeCleanupSettings(record?.ticketCleanupSettings)), [record]);
  useEffect(() => { void (window as any).api?.dbGet?.('workOrders').then((rows: any[]) => setPreview(previewWorkOrderCleanup(rows || [], draft))).catch(() => {}); }, [draft]);
  const numberField = (key: keyof typeof draft, label: string, detail: string) => <label className="rounded-xl border border-zinc-700 bg-zinc-950/60 p-3"><span className="block text-sm font-bold">{label}</span><small className="mt-1 block text-zinc-400">{detail}</small><input aria-label={label} type="number" min={key === 'notRepairableAttentionDays' ? 0 : 1} value={draft[key] as number} onChange={event => setDraft(current => normalizeCleanupSettings({ ...current, [key]: Number(event.target.value) }))} className="mt-3 w-full rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2"/></label>;
  const persist = async () => { const settings = normalizeCleanupSettings(draft); setDraft(settings); await save({ ticketCleanupSettings: settings }); setMessage('Cleanup settings saved and synchronized.'); };
  const run = async () => { await persist(); const result = await reconcileLegacyWorkOrders((window as any).api, { settings: draft }); setMessage(`Cleanup complete: ${result.updated} ticket${result.updated === 1 ? '' : 's'} closed. No payments were changed.`); };
  return <section className="mx-auto h-full max-w-4xl overflow-auto"><h2 className="text-lg font-bold">Ticket Cleanup &amp; Attention</h2><p className="mt-1 text-xs text-zinc-400">Automatically surface stalled work and close legacy tickets while preserving every payment, balance, note, and client record.</p><label className="mt-4 flex items-center gap-3 rounded-xl border border-zinc-700 bg-zinc-950/60 p-4"><input type="checkbox" checked={draft.enabled} onChange={event => setDraft(current => ({ ...current, enabled: event.target.checked }))}/><span><strong className="block">Enable automatic cleanup</strong><small className="text-zinc-400">Runs safely after synchronized work orders load.</small></span></label><div className="mt-3 grid gap-3 md:grid-cols-3">{numberField('notStartedAttentionDays','Not started','Flag checked-in devices with no diagnosis after this many days.')}{numberField('staleAttentionDays','No repair progress','Flag active repairs without technician activity after this many days.')}{numberField('clientResponseAttentionDays','No follow-up after update','Flag client updates with no later action after this many days.')}{numberField('pickupReminderDays','Pickup reminder','Send or flag the pickup reminder after this many days.')}{numberField('pickupAttentionDays','Pickup attention','Escalate uncollected devices after this many days.')}{numberField('notRepairableAttentionDays','Not-repairable attention','Flag a not-repairable device awaiting pickup after this many days.')}{numberField('diagnosticOnlyDays','Diagnostic-only tickets','Close tickets containing only a diagnostic fee after this many days.')}{numberField('closeAllDays','Close every open ticket','Close any remaining open ticket after this many days.')}</div><div className="mt-4 rounded-xl border border-purple-500/50 bg-purple-950/20 p-4"><strong>Preview</strong><div className="mt-2 grid grid-cols-2 gap-2 text-sm sm:grid-cols-4"><span>{preview.scanned} scanned</span><span>{preview.diagnosticOnly} diagnostic-only</span><span>{preview.universal} over-age</span><span className="font-bold text-amber-300">{preview.total} will close</span></div></div><div className="mt-4 flex flex-wrap items-center justify-end gap-3"><span className="mr-auto text-xs text-[#39FF14]">{message}</span><button onClick={() => void persist()} className="rounded-lg border border-zinc-600 px-4 py-2 font-bold">Save</button><button onClick={() => void run()} className="rounded-lg bg-amber-500 px-4 py-2 font-black text-black">Run Cleanup Now</button></div></section>;
}

export default function CatalogSettingsWindow() {
  const payload = consumeWindowPayload('catalogSettings'); const initial = payload === 'repairs' || payload?.tab === 'repairs' || new URLSearchParams(window.location.search).get('settingsTab') === 'repairs' ? 'repairs' : 'inventory'; const [tab, setTab] = useState<'inventory' | 'repairs' | 'pos'>(initial); const [inventoryPane, setInventoryPane] = useState<'types' | 'vendors' | 'defaults'>('types'); const [repairPane, setRepairPane] = useState<'types' | 'devices' | 'defaults'>('types'); const [devices, setDevices] = useState<any[]>([]);
  const reloadDevices = async () => { const rows = await (window as any).api?.dbGet?.('deviceCategories').catch(() => []); setDevices(Array.isArray(rows) ? rows : []); }; useEffect(() => { void reloadDevices(); const off = (window as any).api?.onDeviceCategoriesChanged?.(() => void reloadDevices()); return () => { try { off?.(); } catch {} }; }, []);
  const navButton = (active: boolean) => `shrink-0 rounded-lg border px-3 py-2 text-sm font-bold ${active ? 'border-purple-400 bg-purple-500/15 text-purple-200' : 'border-zinc-700 text-zinc-300'}`;
  return <div className="flex h-screen flex-col overflow-hidden bg-zinc-900 p-3 text-zinc-100 sm:p-4"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-zinc-700 pb-3"><div><h1 className="text-xl font-black">POS Settings</h1><p className="text-xs text-zinc-400">Synchronized shop, catalog, and workflow settings.</p></div><div className="flex rounded-xl border border-zinc-700 bg-zinc-950 p-1"><button onClick={() => setTab('inventory')} className={`rounded-lg px-4 py-2 text-sm font-bold ${tab === 'inventory' ? 'bg-[#39FF14] text-black' : ''}`}>Inventory</button><button onClick={() => setTab('repairs')} className={`rounded-lg px-4 py-2 text-sm font-bold ${tab === 'repairs' ? 'bg-[#39FF14] text-black' : ''}`}>Repairs</button><button onClick={() => setTab('pos')} className={`rounded-lg px-4 py-2 text-sm font-bold ${tab === 'pos' ? 'bg-[#39FF14] text-black' : ''}`}>POS</button></div></header>{tab !== 'pos' ? <div className="mt-3 flex shrink-0 gap-2 overflow-x-auto pb-2">{tab === 'inventory' ? <><button className={navButton(inventoryPane === 'types')} onClick={() => setInventoryPane('types')}>Part Types</button><button className={navButton(inventoryPane === 'vendors')} onClick={() => setInventoryPane('vendors')}>Distributors / Vendors</button><button className={navButton(inventoryPane === 'defaults')} onClick={() => setInventoryPane('defaults')}>Defaults</button></> : <><button className={navButton(repairPane === 'types')} onClick={() => setRepairPane('types')}>Repair Types</button><button className={navButton(repairPane === 'devices')} onClick={() => setRepairPane('devices')}>Devices</button><button className={navButton(repairPane === 'defaults')} onClick={() => setRepairPane('defaults')}>Defaults</button></>}</div> : null}<main className="min-h-0 flex-1 overflow-hidden pt-1">{tab === 'pos' ? <TicketCleanupSettings/> : tab === 'inventory' ? inventoryPane === 'types' ? <InventoryTypesSettings/> : inventoryPane === 'vendors' ? <VendorsWindow embedded/> : <DefaultsSettings kind="inventory"/> : repairPane === 'types' ? <RepairTypeManager/> : repairPane === 'devices' ? <DeviceForm titles={Array.from(new Set(devices.map(row => String(row?.title || '')).filter(Boolean)))} devices={devices} onCancel={() => setRepairPane('types')} onSaved={reloadDevices}/> : <DefaultsSettings kind="repairs"/>}</main></div>;
}
