import React, { useEffect, useMemo, useState } from 'react';
import RepairTypeManager from '../repairs/RepairTypeManager';
import DeviceForm from '../repairs/DeviceForm';
import VendorsWindow from './VendorsWindow';
import { consumeWindowPayload } from '../lib/windowPayload';
import { normalizeInventoryDefaults, normalizeRepairDefaults } from '../lib/catalogDefaults';

const DEFAULT_PART_TYPES = ['Screen', 'Battery', 'Charging Port', 'Camera', 'Speaker', 'Microphone', 'Buttons', 'Housing', 'Motherboard', 'Power Supply', 'Cable', 'Adhesive', 'Other'];
function useShopSettings() { const api = (window as any).api; const [record, setRecord] = useState<any>({}); useEffect(() => { void api?.dbGet?.('settings').then((rows: any[]) => setRecord(Array.isArray(rows) ? rows[0] || {} : {})).catch(() => {}); }, [api]); async function save(patch: any) { const payload = { ...record, ...patch, updatedAt: new Date().toISOString() }; const saved = record?.id != null ? await api?.dbUpdate?.('settings', record.id, payload) : await api?.dbAdd?.('settings', { ...payload, createdAt: new Date().toISOString() }); setRecord({ ...payload, ...(saved || {}) }); } return { record, save }; }

function InventoryTypesSettings() {
  const { record, save: saveSettings } = useShopSettings(); const [types, setTypes] = useState<string[]>(DEFAULT_PART_TYPES); const [value, setValue] = useState(''); const [editing, setEditing] = useState('');
  useEffect(() => { if (Array.isArray(record?.inventoryPartTypes) && record.inventoryPartTypes.length) setTypes(record.inventoryPartTypes); }, [record]);
  const sorted = useMemo(() => [...types].sort((a, b) => a.localeCompare(b)), [types]);
  async function persist(next: string[]) { const normalized = Array.from(new Set(next.map(item => item.trim()).filter(Boolean))); setTypes(normalized); await saveSettings({ inventoryPartTypes: normalized }); }
  async function commit() { const name = value.trim(); if (!name) return; await persist(editing ? types.map(item => item === editing ? name : item) : [...types, name]); setValue(''); setEditing(''); }
  return <section className="flex h-full min-h-0 flex-col"><div><h2 className="text-lg font-bold">Part Types</h2><p className="mt-1 text-xs text-zinc-400">Manage the saved choices used by the Inventory Part Type field.</p></div><div className="mt-4 flex flex-wrap gap-2"><input value={value} onChange={event => setValue(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') void commit(); }} placeholder={editing ? 'Rename part type' : 'Add part type'} className="min-w-[190px] flex-1 rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2 outline-none focus:border-[#39FF14]"/><button onClick={() => void commit()} className="rounded-lg bg-[#39FF14] px-4 font-bold text-black">{editing ? 'Rename' : 'Add'}</button>{editing ? <button onClick={() => { setEditing(''); setValue(''); }} className="rounded-lg border border-zinc-700 px-3">Cancel</button> : null}</div><div className="mt-4 min-h-0 flex-1 overflow-auto rounded-xl border border-zinc-700 bg-zinc-950/50">{sorted.map(type => <div key={type} className="flex items-center justify-between border-b border-zinc-800 px-4 py-3 last:border-0"><strong>{type}</strong><div className="flex gap-2"><button onClick={() => { setEditing(type); setValue(type); }} className="rounded border border-zinc-700 px-3 py-1 text-xs">Edit</button><button onClick={() => void persist(types.filter(item => item !== type))} className="rounded border border-red-500/60 px-3 py-1 text-xs text-red-300">Remove</button></div></div>)}</div></section>;
}

function DefaultsSettings({ kind }: { kind: 'inventory' | 'repairs' }) {
  const { record, save } = useShopSettings(); const current = useMemo(() => kind === 'inventory' ? normalizeInventoryDefaults(record?.inventoryDefaults) : normalizeRepairDefaults(record?.repairDefaults), [kind, record]); const [draft, setDraft] = useState<any>(current); const [saved, setSaved] = useState(false); useEffect(() => setDraft(current), [current]);
  const field = (key: string, label: string, type = 'number') => <label className="block"><span className="mb-1 block text-xs font-semibold text-zinc-400">{label}</span><input type={type} value={draft[key] ?? ''} onChange={event => setDraft((value: any) => ({ ...value, [key]: type === 'number' ? Number(event.target.value) : event.target.value }))} className="w-full rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2 outline-none focus:border-[#39FF14]"/></label>;
  return <section className="mx-auto h-full max-w-3xl overflow-auto"><h2 className="text-lg font-bold">{kind === 'inventory' ? 'Inventory Defaults' : 'Repair Defaults'}</h2><p className="mt-1 text-xs text-zinc-400">Defaults apply only to new entries. Existing records are never overwritten.</p><div className="mt-5 grid gap-4 rounded-xl border border-zinc-700 bg-zinc-950/50 p-4 sm:grid-cols-2">{kind === 'inventory' ? <>{field('markupPct', 'Default Markup %')}{field('lowStockThreshold', 'Low Stock Threshold')}{field('reorderQty', 'Default Reorder Quantity')}<label className="block"><span className="mb-1 block text-xs font-semibold text-zinc-400">Condition Choices</span><input value={(draft.conditions || []).join(', ')} onChange={event => setDraft((value: any) => ({ ...value, conditions: event.target.value.split(',').map((item: string) => item.trim()).filter(Boolean) }))} className="w-full rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2"/></label></> : <>{field('repairCategory', 'Default Repair Type', 'text')}{field('laborCost', 'Default Labor Charge')}</>}</div><div className="mt-4 flex items-center justify-end gap-3"><span className="text-xs text-[#39FF14]">{saved ? 'Defaults saved.' : ''}</span><button onClick={() => void save(kind === 'inventory' ? { inventoryDefaults: normalizeInventoryDefaults(draft) } : { repairDefaults: normalizeRepairDefaults(draft) }).then(() => { setSaved(true); window.setTimeout(() => setSaved(false), 2500); })} className="rounded-lg bg-[#39FF14] px-5 py-2 text-sm font-bold text-black">Save Defaults</button></div></section>;
}

export default function CatalogSettingsWindow() {
  const payload = consumeWindowPayload('catalogSettings'); const initial = payload === 'repairs' || payload?.tab === 'repairs' || new URLSearchParams(window.location.search).get('settingsTab') === 'repairs' ? 'repairs' : 'inventory'; const [tab, setTab] = useState<'inventory' | 'repairs'>(initial); const [inventoryPane, setInventoryPane] = useState<'types' | 'vendors' | 'defaults'>('types'); const [repairPane, setRepairPane] = useState<'types' | 'devices' | 'defaults'>('types'); const [devices, setDevices] = useState<any[]>([]);
  const reloadDevices = async () => { const rows = await (window as any).api?.dbGet?.('deviceCategories').catch(() => []); setDevices(Array.isArray(rows) ? rows : []); }; useEffect(() => { void reloadDevices(); const off = (window as any).api?.onDeviceCategoriesChanged?.(() => void reloadDevices()); return () => { try { off?.(); } catch {} }; }, []);
  const navButton = (active: boolean) => `shrink-0 rounded-lg border px-3 py-2 text-sm font-bold ${active ? 'border-purple-400 bg-purple-500/15 text-purple-200' : 'border-zinc-700 text-zinc-300'}`;
  return <div className="flex h-screen flex-col overflow-hidden bg-zinc-900 p-3 text-zinc-100 sm:p-4"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-zinc-700 pb-3"><div><h1 className="text-xl font-black">Catalog Settings</h1><p className="text-xs text-zinc-400">Saved choices shared by Inventory and Repairs.</p></div><div className="flex rounded-xl border border-zinc-700 bg-zinc-950 p-1"><button onClick={() => setTab('inventory')} className={`rounded-lg px-4 py-2 text-sm font-bold ${tab === 'inventory' ? 'bg-[#39FF14] text-black' : ''}`}>Inventory</button><button onClick={() => setTab('repairs')} className={`rounded-lg px-4 py-2 text-sm font-bold ${tab === 'repairs' ? 'bg-[#39FF14] text-black' : ''}`}>Repairs</button></div></header><div className="mt-3 flex shrink-0 gap-2 overflow-x-auto pb-2">{tab === 'inventory' ? <><button className={navButton(inventoryPane === 'types')} onClick={() => setInventoryPane('types')}>Part Types</button><button className={navButton(inventoryPane === 'vendors')} onClick={() => setInventoryPane('vendors')}>Distributors / Vendors</button><button className={navButton(inventoryPane === 'defaults')} onClick={() => setInventoryPane('defaults')}>Defaults</button></> : <><button className={navButton(repairPane === 'types')} onClick={() => setRepairPane('types')}>Repair Types</button><button className={navButton(repairPane === 'devices')} onClick={() => setRepairPane('devices')}>Devices</button><button className={navButton(repairPane === 'defaults')} onClick={() => setRepairPane('defaults')}>Defaults</button></>}</div><main className="min-h-0 flex-1 overflow-hidden pt-1">{tab === 'inventory' ? inventoryPane === 'types' ? <InventoryTypesSettings/> : inventoryPane === 'vendors' ? <VendorsWindow embedded/> : <DefaultsSettings kind="inventory"/> : repairPane === 'types' ? <RepairTypeManager/> : repairPane === 'devices' ? <DeviceForm titles={Array.from(new Set(devices.map(row => String(row?.title || '')).filter(Boolean)))} devices={devices} onCancel={() => setRepairPane('types')} onSaved={reloadDevices}/> : <DefaultsSettings kind="repairs"/>}</main></div>;
}
